### ISSUE TITLE
flash_read_data in v1 mask ROM

### ISSUE THREAD

**Issue by CDK-Vonkil** [raspberrypi/pico-bootrom#16]
```
void __noinline flash_read_data(uint32_t addr, uint8_t *rx, size_t count) {
    assert(addr < 0x1000000);
    flash_put_cmd_addr(FLASHCMD_READ_DATA, addr);
    flash_put_get(NULL, rx, count, 4);
}
```

Here is the disassembly of what appears in the v1 mask ROM:
```
flash_read_data:
    17e0:	b510      	push	{r4, lr}
    17e2:	000c      	movs	r4, r1
    17e4:	0001      	movs	r1, r0
    17e6:	2003      	movs	r0, #3
    17e8:	f7ff f9da 	bl	0xba0 ; flash_put_cmd_addr
    17ec:	2280      	movs	r2, #128	; 0x80
    17ee:	2304      	movs	r3, #4
    17f0:	0021      	movs	r1, r4
    17f2:	2000      	movs	r0, #0
    17f4:	0052      	lsls	r2, r2, #1
    17f6:	f7ff ffbf 	bl	0x1778 ; flash_put_get
    17fa:	bd10      	pop	{r4, pc}
```

One will notice that upon entry: `r0=addr`, `r1=rx`, and `r2=count`.  `r4` is used as a temporary.  Argument shuffling is done prior to the call of `flash_put_cmd_addr( )`, which proceeds as expected.  However, notice what happens to the arguments for `flash_put_get( )`.  `r0=0` (NULL), `r1=rx` (previously saved in `r4`), `r3=4`.  But `r2=0x80<<1=256`!  

The build appears to have optimized `flash_read_data( )` to perform only `count=256`.

This is not an outright bug.  But it certainly makes `flash_read_data( )` not work as advertised, should it ever be called from outside the mask ROM (which is exactly what I had wished to do in a custom 2nd stage bootloader).

**Comment by kilograham** [comment]
yup, that isn't a public function, and it is only called by the bootrom with 256 as the argument it seems.

if you look at the actual build DIS you'll see the mangled function name

```
000017e0 <flash_read_data.constprop.0>:
    17e0:	b510      	push	{r4, lr}
    17e2:	000c      	movs	r4, r1
    17e4:	0001      	movs	r1, r0
    17e6:	2003      	movs	r0, #3
    17e8:	f7ff f9da 	bl	ba0 <flash_put_cmd_addr>
    17ec:	2280      	movs	r2, #128	; 0x80
    17ee:	2304      	movs	r3, #4
    17f0:	0021      	movs	r1, r4
    17f2:	2000      	movs	r0, #0
    17f4:	0052      	lsls	r2, r2, #1
    17f6:	f7ff ffbf 	bl	1778 <flash_put_get>
    17fa:	bd10      	pop	{r4, pc}
```

Perhaps open another issue with bootrom functions that you think are useful and should be public.

**Comment by kilograham** [comment]
(note public functions are ones in the function tables)

**Comment by CDK-Vonkil** [comment]
This is all reasonable.

A few parting comments.  

Presumably `flash_read_data` is `noinline` for a reason.  Given its limited invocation and the 256-byte optimization already observed, it appears worth investigation as to whether it is more efficient, in both space and speed, to simply inline it.

Given I need to work with existing mask ROMs, there seems little point in requesting `flash_read_data` be exported.  It appears that `flash_put_cmd_addr` and `flash_put_get` are intact in the mask ROM.  By intact I mean they fully live up to the signature of their function prototypes.  Perhaps those are too primitive to ever officially export, but these are the ones I will now focus on.

And finally, my other issue #15 was recently posted because this project's build does not "just work" for me on a fully up-to-date Fedora Linux box.  Probably user error, but I don't really want to build the project anyway.  I just want symbol locations and disassembly, something along the lines of what was posted to this issue.  Since I cannot reproduce the build without hacking my kit, there is no way for me to know if any local workarounds have produced a result different to those submitted to the semiconductor fab house.

**Comment by lurch** [comment]
If you're poking around at undocumented functions in the bootrom, rather than only using those functions that have been publicly documented, I guess there's a slight risk that you might use functions which get removed from the bootrom in a possible future RP2040 chip? :man_shrugging:

**Comment by CDK-Vonkil** [comment]
> 

"undocumented" does not have a definition in the open-source dictionary :-)

But seriously, of course you are right, but with a 256-byte limit for a 2nd stage bootloader, one must seek fixed resources wherever they may be found.

**Comment by kilograham** [comment]
> Presumably `flash_read_data` is `noinline` for a reason.

Almost certainly because of size; there are only a handful of bytes free in the ROM
