### ISSUE TITLE
Bootstrap for boot configuration in XIP or GPIO pins

### ISSUE THREAD

**Issue by daveythacher** [raspberrypi/pico-bootrom#23]
It would appear USB boot loader requires a specific clock source. The configuration of the clock may allow for more support. Currently a boot loader is required to work around this problem. An alternative is to look up the settings in flash or trigger a different process via GPIO.

**Comment by lurch** [comment]
I can't tell what you're asking for (do you have a question?), but do sections 2.7 and 2.8 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf answer your query? Section 1.4.2 also says "The USB bootloader requires a 12MHz crystal or 12MHz clock input.".

**Comment by daveythacher** [comment]
The 2nd stage payload could be extended to add support for other configurations.

**Comment by Wren6991** [comment]
Adding GPIO straps would break compatibility with existing PCB designs. As you say this can be solved today with a flash-resident USB bootloader, and if you put configuration data in flash then you could just as easily put code in there.

We don't plan to make any ROM changes to address this. The ROM USB bootloader requires a 12 MHz crystal across XIN and XOUT.

**Comment by daveythacher** [comment]
In all fairness this issue could have been worked around with GPCLK PPL. 

Does the SDK have any plans for a flash boot loader stub? The way I see it you could produce two here. One for bringing up the SDK and one for actually replacing the ROM boot loader. The later version could replace USB comms with something else if done correctly. The problem here is the SDK would need to lead this project at some point.

A modular ROM boot loader would have made more sense. Configuration and comms could have been modular with a default of USB in ROM. Any chance of this being included in RP235x? Note existing compatibility requires this to be placed into a reserved address space, which represents potential issues.

Overall I guess I would have preferred a more open ended solution for the ROM that could have been managed in software. I tend to agree with the idea that this could be implemented in SDK. However my question is will you?

**Comment by lurch** [comment]
I've not looked at any of them myself, but you may find one of the third-party bootloaders interesting? https://www.google.com/search?q=pico+flash+bootloader
