### ISSUE TITLE
source code doesn't match mask ROM?

### ISSUE THREAD

**Issue by majbthrd** [raspberrypi/pico-bootrom#4]
I have been unable to re-create an image that matches the RP2040 mask ROM, at least on the parts that I have.  There are non-trivial differences.

Having an .elf file to trace through Boot ROM code execution is rather important in diagnosing RP2040 behavior.

I’m using this to compile (which ostensibly matches what the README says):

gcc version 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599] (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 

The 8 most significant hex digits of the Bootrom git revision are: 0xd24340e4

The bootrom version byte at 0x13 is 0x01

How any of this relates to the “B1” specified in the README is not clear.

The README also speaks of “built in debug mode”.  I’ve tried both:

cmake -DCMAKE_BUILD_TYPE=Debug .
cmake  .

without any change in the output file.

I've attached a binary of what the mask ROM is on the parts that I have.

[rp2040maskrom.zip](https://github.com/raspberrypi/pico-bootrom/files/5940346/rp2040maskrom.zip)

Thanks.

**Comment by kilograham** [comment]
The file you sent it the B0 bootrom from a device.
So you need to build the B0 tag (which should match except for the git revision) - it may be harder to match the compiler on that one tho.

**Comment by Wren6991** [comment]
> The bootrom version byte at 0x13 is 0x01

What you have there is a B0 device, so you need to look at [the B0 tag on github](https://github.com/raspberrypi/pico-bootrom/tree/b0) where you will see this:

```
.global _magic
_magic:
# magic
.byte 'M', 'u'
# compatibility version (change if function table is incompatible, or functions are backwards incompatible)
.byte 1
# ROM version
.byte 1
```

As opposed to B1.

> The 8 most significant hex digits of the Bootrom git revision are: 0xd24340e4

Yes the git hash is different because the history is squashed. This is how git generates its hashes.

**Comment by Wren6991** [comment]
17 seconds apart, not bad :)

**Comment by majbthrd** [comment]
Got it.  Thanks!
