### ISSUE TITLE
Running _connect_internal_flash from the debugger often fails

### ISSUE THREAD

**Issue by UweBonnes** [raspberrypi/pico-bootrom#7]
Hello,

The blackmagic debugger now handles multidrop, detects the RP Pico and implement Erase/flash via the ROM functions via the trampoline via the debugger: https://github.com/blacksphere/blackmagic/pull/843

As test, I use the debug build of pico-examples/blink. Flashing with BMP hosted  like "blackmagic blink/blink.bin" mostly works. However often, the first call to  _connect_internal_flash() fails and PC ends up as 0x100001c4, that is the hardfault handler of blink.  Running with the bmp gdb server in firmware always fail, here no usb transactions happen but introducings delay did not help neither.

Any hints welcome!

**Comment by UweBonnes** [comment]
I forgot the set up the thumb bit , bit 24 in XPSR when calling into the ROM.

**Comment by kilograham** [comment]
it's always the thumb bit :-)

**Comment by UweBonnes** [comment]
Really ;)

Can you perhaps have a look at https://github.com/blacksphere/blackmagic/pull/857 as a Rp2040 debugger? Blackmagic runs a PC hosted gdb server with Blackmagic probes, ftdi, cmsis-dap and jlink probes and the gdb server also on the probe for blackmagic firmware probes.  Stlinks can not handle Multidrop, but firmware may get replaced with blackmagic firmware.

Programmming speed is around 14kB/s. What do other debuggers achieve?

With hosted , flashing is as simple as "blackmagic <file.bin>"

**Comment by kilograham** [comment]
you can mention it over and pico-feedback repository
