### ISSUE TITLE
master branch fails to build with ld: bootrom.elf section '.text' will not fit in region `ROM'

### ISSUE THREAD

**Issue by 06needhamt** [raspberrypi/pico-bootrom#8]
See below for the full error message.

```
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bootrom.elf section `.text' will not fit in region `ROM'
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: region `ROM' overflowed by 16384 bytes
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by aallan** [comment]
> `ninja: build stopped: subcommand failed.`

Using `ninja` suggests you are attempting to build the bootrom on Windows? Can you provide some more details of your environment.

**Comment by 06needhamt** [comment]
I am trying to build on archlinux. I always prefer to use Ninja over makefiles where possible as it seems to be faster on my machine is this not a supported configuration

**Comment by kilograham** [comment]
you very much need to build with the version of GCC suggested in the readme.

**Comment by aallan** [comment]
>  …is this not a supported configuration

Nope.
